/*
 * Desktop App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ItemsPublic {
    #[serde(rename = "data")]
    pub data: Vec<models::ItemPublic>,
    #[serde(rename = "count")]
    pub count: i32,
}

impl ItemsPublic {
    pub fn new(data: Vec<models::ItemPublic>, count: i32) -> ItemsPublic {
        ItemsPublic {
            data,
            count,
        }
    }
}

