/*
 * Desktop App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UpdatePassword {
    #[serde(rename = "current_password")]
    pub current_password: String,
    #[serde(rename = "new_password")]
    pub new_password: String,
}

impl UpdatePassword {
    pub fn new(current_password: String, new_password: String) -> UpdatePassword {
        UpdatePassword {
            current_password,
            new_password,
        }
    }
}

