/*
 * Desktop App
 *
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct UsersPublic {
    #[serde(rename = "data")]
    pub data: Vec<models::UserPublic>,
    #[serde(rename = "count")]
    pub count: i32,
}

impl UsersPublic {
    pub fn new(data: Vec<models::UserPublic>, count: i32) -> UsersPublic {
        UsersPublic {
            data,
            count,
        }
    }
}

